POST http://localhost:8080/api/auth/register HTTP/1.1
Content-Type: application/json

{
    "name":"nashir",
    "email":"myemail@myemail.com",
    "password":"rental",
    "address":"kra",
    "photo":"png",
    "role":"admin"
}
###